
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Feb 07 03:01:25 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 25;
  public static final int CONST = 4;
  public static final int LPAREN = 27;
  public static final int SEMI = 6;
  public static final int CONTINUE = 13;
  public static final int LESS = 34;
  public static final int RPAREN = 28;
  public static final int GRE = 32;
  public static final int BOTTLINE = 8;
  public static final int AND = 36;
  public static final int RECORD = 46;
  public static final int DIFFER = 31;
  public static final int OR = 37;
  public static final int COMMA = 5;
  public static final int CLASS = 16;
  public static final int INC = 44;
  public static final int DIV = 41;
  public static final int DIGIT = 48;
  public static final int PLUS = 38;
  public static final int MIN = 39;
  public static final int LESSEQ = 35;
  public static final int IF = 21;
  public static final int DOT = 43;
  public static final int BOOLEAN = 49;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int RBRACKET = 26;
  public static final int EQUAL = 29;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int MUL = 40;
  public static final int DASH = 9;
  public static final int MOD = 42;
  public static final int BREAK = 12;
  public static final int IDENT = 3;
  public static final int VOID = 15;
  public static final int SAME = 30;
  public static final int LBRACE = 23;
  public static final int ELSE = 22;
  public static final int LETTER = 47;
  public static final int READ = 19;
  public static final int GOTO = 20;
  public static final int WHILE = 11;
  public static final int RBRACE = 24;
  public static final int EXTENDS = 17;
  public static final int PROG = 2;
  public static final int GREEQ = 33;
  public static final int DEC = 45;
  public static final int PRINT = 18;
  public static final int DO = 10;
}

