
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Sep 14 06:31:02 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 45;
  public static final int LBRACKET = 9;
  public static final int CONST = 3;
  public static final int LPAREN = 7;
  public static final int SEMI = 6;
  public static final int CONTINUE = 31;
  public static final int INCINC = 54;
  public static final int REVERSE = 53;
  public static final int CHARACTER = 17;
  public static final int RPAREN = 8;
  public static final int AND = 46;
  public static final int LT = 44;
  public static final int RECORD = 27;
  public static final int OR = 47;
  public static final int COMMA = 14;
  public static final int CLASS = 23;
  public static final int INC = 34;
  public static final int DIV = 38;
  public static final int PLUS = 13;
  public static final int MIN = 36;
  public static final int ASSIGN = 11;
  public static final int IF = 21;
  public static final int THIS = 50;
  public static final int DOT = 25;
  public static final int EOF = 0;
  public static final int BOOLEAN = 19;
  public static final int RETURN = 12;
  public static final int RBRACKET = 10;
  public static final int SUPER = 52;
  public static final int NEW = 48;
  public static final int error = 1;
  public static final int ISNULL = 49;
  public static final int MUL = 37;
  public static final int MOD = 39;
  public static final int NUMBER = 18;
  public static final int NEQ = 41;
  public static final int BREAK = 30;
  public static final int IDENT = 20;
  public static final int VOID = 16;
  public static final int EQ = 40;
  public static final int GTE = 43;
  public static final int COLON = 26;
  public static final int LBRACE = 4;
  public static final int ELSE = 22;
  public static final int ENUM = 51;
  public static final int READ = 32;
  public static final int GOTO = 33;
  public static final int WHILE = 29;
  public static final int RBRACE = 5;
  public static final int EXTENDS = 24;
  public static final int PROG = 2;
  public static final int DEC = 35;
  public static final int MAX = 55;
  public static final int GT = 42;
  public static final int PRINT = 15;
  public static final int DO = 28;
}

